"""empty message

Revision ID: 3056e7f4a8b4
Revises: 60f35a1b51d4
Create Date: 2021-01-16 14:21:00.445983

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3056e7f4a8b4'
down_revision = '60f35a1b51d4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('item_info',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('info', sa.String(length=16), nullable=True),
    sa.Column('type', sa.String(length=16), nullable=True),
    sa.Column('image', sa.String(length=128), nullable=True),
    sa.Column('desc', sa.String(length=1024), nullable=True),
    sa.Column('date', sa.DateTime(), nullable=True),
    sa.Column('place', sa.String(length=64), nullable=True),
    sa.Column('campus', sa.String(length=32), nullable=True),
    sa.Column('uid', sa.String(length=16), nullable=True),
    sa.Column('is_claim', sa.Boolean(), nullable=True),
    sa.Column('is_delete', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['type'], ['item_type.type'], ),
    sa.ForeignKeyConstraint(['uid'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('item_info')
    # ### end Alembic commands ###
