"""empty message

Revision ID: 8f942101b30f
Revises: b4da45029a2c
Create Date: 2021-01-17 21:19:18.015070

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8f942101b30f'
down_revision = 'b4da45029a2c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('item_info',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('info', sa.String(length=16), nullable=True),
    sa.Column('type', sa.String(length=16), nullable=True),
    sa.Column('image', sa.String(length=128), nullable=True),
    sa.Column('desc', sa.String(length=1024), nullable=True),
    sa.Column('date', sa.DateTime(), nullable=True),
    sa.Column('place', sa.String(length=64), nullable=True),
    sa.Column('campus', sa.String(length=32), nullable=True),
    sa.Column('uid', sa.String(length=16), nullable=True),
    sa.Column('is_claim', sa.Boolean(), nullable=True),
    sa.Column('is_delete', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['type'], ['item_type.type'], ondelete='SET DEFAULT'),
    sa.ForeignKeyConstraint(['uid'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('item_info')
    # ### end Alembic commands ###
