"""empty message

Revision ID: b4da45029a2c
Revises: 802f0c79958d
Create Date: 2021-01-17 20:10:04.234619

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b4da45029a2c'
down_revision = '802f0c79958d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('item_info_ibfk_3', 'item_info', type_='foreignkey')
    op.create_foreign_key(None, 'item_info', 'item_type', ['type'], ['type'], ondelete='SET DEFAULT')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'item_info', type_='foreignkey')
    op.create_foreign_key('item_info_ibfk_3', 'item_info', 'item_type', ['type'], ['type'])
    # ### end Alembic commands ###
