"""empty message

Revision ID: e4258b56301f
Revises: 349966e48e07
Create Date: 2021-01-18 15:14:40.516417

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e4258b56301f'
down_revision = '349966e48e07'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('notice',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('title', sa.String(length=128), nullable=True),
    sa.Column('content', sa.String(length=1024), nullable=True),
    sa.Column('type', sa.String(length=32), nullable=True),
    sa.Column('creator', sa.String(length=32), nullable=True),
    sa.Column('date', sa.DateTime(), nullable=True),
    sa.Column('is_delete', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_constraint('item_info_ibfk_1', 'item_info', type_='foreignkey')
    op.create_foreign_key(None, 'item_info', 'item_type', ['type'], ['type'], ondelete='SET DEFAULT')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'item_info', type_='foreignkey')
    op.create_foreign_key('item_info_ibfk_1', 'item_info', 'item_type', ['type'], ['type'])
    op.drop_table('notice')
    # ### end Alembic commands ###
